### PR TITLE
Reige012-Submission Assignment 1

### PR DESCRIPTION
**Pull request by reige012**

### CODE REVIEW

**Comment by brantfaircloth** [comment]
Alicia - this removes the `README.md` file in the assignment-1 directory... which we don't want to do.  So, you'll need to fix your repository so that this is not the case.  I'm closing this pull request - please submit a new one when you have the issue fixed.

**Comment by reige012** [comment]
Ok, im not sure what that means, but i will look....

Sorry!!!

On Friday, January 15, 2016, Brant Faircloth <notifications@github.com>
wrote:

> Alicia - this removes the README.md file in the assignment-1 directory...
> which we don't want to do. So, you'll need to fix your repository so that
> this is not the case. I'm closing this pull request - please submit a new
> one when you have the issue fixed.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/biolprogramming/assignment-1/pull/3#issuecomment-172004303>
> .
>


-- 
Ph.D. Student, Louisiana State University
M.S. Biology, Georgia Southern University
Phone: (912)481-5298
Email: areige1@lsu.edu

**Comment by brantfaircloth** [comment]
no sweat.  i expect some of these hiccups as we get going.  easiest 
would be to “start-over” - copy your files to a temporary location, 
then do the fork - clone - sync - pull request dance again.

there are other way to do it… but that’s probably easiest for now.

-b

**Comment by reige012** [comment]
Ok, sorry I tried deleting my folder and now it says something weird about
how I reverted something on the github page?

On Friday, January 15, 2016, Brant Faircloth <notifications@github.com>
wrote:

> no sweat. i expect some of these hiccups as we get going. easiest
> would be to “start-over” - copy your files to a temporary location,
> then do the fork - clone - sync - pull request dance again.
>
> there are other way to do it… but that’s probably easiest for now.
>
> -b
>
> On 15 Jan 2016, at 10:18, Alicia Reigel wrote:
>
> > Ok, im not sure what that means, but i will look....
> >
> > Sorry!!!
> >
> > On Friday, January 15, 2016, Brant Faircloth
> > <notifications@github.com
> <javascript:_e(%7B%7D,'cvml','notifications@github.com');>>
> > wrote:
> >
> >> Alicia - this removes the README.md file in the assignment-1
> >> directory...
> >> which we don't want to do. So, you'll need to fix your repository so
> >> that
> >> this is not the case. I'm closing this pull request - please submit a
> >> new
> >> one when you have the issue fixed.
> >>
> >> —
> >> Reply to this email directly or view it on GitHub
> >> <
> https://github.com/biolprogramming/assignment-1/pull/3#issuecomment-172004303
> >
> >> .
> >>
> >
> >
> > --
> > Ph.D. Student, Louisiana State University
> > M.S. Biology, Georgia Southern University
> > Phone: (912)481-5298
> > Email: areige1@lsu.edu <javascript:_e(%7B%7D,'cvml','areige1@lsu.edu');>
> >
> >
> > ---
> > Reply to this email directly or view it on GitHub:
> >
> https://github.com/biolprogramming/assignment-1/pull/3#issuecomment-172004544
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/biolprogramming/assignment-1/pull/3#issuecomment-172004909>
> .
>


-- 
Ph.D. Student, Louisiana State University
M.S. Biology, Georgia Southern University
Phone: (912)481-5298
Email: areige1@lsu.edu

**Comment by brantfaircloth** [comment]
On 15 Jan 2016, at 10:37, Alicia Reigel wrote:

> Ok, sorry I tried deleting my folder and now it says something weird 
> about
> how I reverted something on the github page?

will leave that up to you to figure out.  you may need to delete the 
repository on your github account (go to settings) and start over…

-b

**Pull request closed without merging**
