### PR TITLE
Master

### PR DESCRIPTION
**Pull request by sthshraddha**

### CODE REVIEW

**Comment by brantfaircloth** [comment]
hi Shraddha,

this is missing most of the screenshots and most of the ipython notebook.

-b

**Comment by sthshraddha** [comment]
Hmmm i forgot to add two screenshots and i tried to add them to my repository. Should i retry to submit my answers folder?

Sent from my iPhone

On Jan 19, 2016, at 8:36 AM, Brant Faircloth <notifications@github.com<mailto:notifications@github.com>> wrote:


hi Shraddha,

this is missing most of the screenshots and most of the ipython notebook.

-b

-

**Comment by brantfaircloth** [comment]
you are also missing many of the answers to the tasks for ipython.  you 
can add all of that to your folder and resubmit the pull request once 
you’ve added those items, committed them, pushed that to your 
repository, and made the pull request.

-b

**Comment by sthshraddha** [comment]
Man! Okay i will resubmit the folder again.

Sent from my iPhone

On Jan 19, 2016, at 8:55 AM, Brant Faircloth <notifications@github.com<mailto:notifications@github.com>> wrote:

you are also missing many of the answers to the tasks for ipython. you
can add all of that to your folder and resubmit the pull request once
you've added those items, committed them, pushed that to your
repository, and made the pull request.

-b


On 19 Jan 2016, at 8:51, sthshraddha wrote:

> Hmmm i forgot to add two screenshots and i tried to add them to my
> repository. Should i retry to submit my answers folder?
>
> Sent from my iPhone
>
> On Jan 19, 2016, at 8:36 AM, Brant Faircloth
> <notifications@github.com<mailto:notifications@github.com><mailto:notifications@github.com>> wrote:
>
>
> hi Shraddha,
>
> this is missing most of the screenshots and most of the ipython
> notebook.
>
> -b
>
> -
> Reply to this email directly or view it on
> GitHub<https://github.com/biolprogramming/assignment-1/pull/15#issuecomment-172871773>.
>
>
> ---
> Reply to this email directly or view it on GitHub:
> https://github.com/biolprogramming/assignment-1/pull/15#issuecomment-172876268

-

**Comment by sthshraddha** [comment]
This is how my github repository looks like. All the files look like it is there


[cid:9f5a6b52-060f-4fbf-b609-a59ed93a4069]

________________________________

**Comment by brantfaircloth** [comment]
On 19 Jan 2016, at 8:59, sthshraddha wrote:

> This is how my github repository looks like. All the files look like 
> it is there

yep, i agree it looks ok.  try the pull request now.

-b

**Comment by sthshraddha** [comment]
Can u see it in the folder now?


________________________________

**Pull request closed without merging**
