### PR TITLE
Master

### PR DESCRIPTION
**Pull request by pramodpantha**

### CODE REVIEW

**Comment by brantfaircloth** [comment]
this still is not correct.  remove the files that are not in the directory having your name.

**Comment by pramodpantha** [comment]
In re-submission directory I think all files have my name, do you mean in other directories that I submitted before? or something else? I could not figure it out.

**Comment by brantfaircloth** [comment]
I'm not sure I can repeat the same thing over and over much more.  take a look at other peoples files.  every file needs to be in a single folder that has your github name.  no files should be directly in the "results" folder.

-b

**Comment by brantfaircloth** [comment]
pramod,

can you come by my office tomorrow morning?  i can help you get things setup correctly.

-b

**Comment by brantfaircloth** [comment]
pramod,

also, this may help - the files need to be organized like:

```
answers/
    pramodpantha/
        Anaconda_REPL.docx
        Assignment 1.ipynb
        github account created.docx
        ...
```

-b

**Comment by pramodpantha** [comment]
Thank you Dr. Brant.

I will try tonight few more time and if still not solved then I will come to your office tomorrow morning.

Thanks.

**Comment by brantfaircloth** [comment]
Sounds good.  You are very close.  Also, since you have the basic files and everything you need to submit, i won't be taking any points off for being late... so don't worry about your score on this assignment.

**Comment by pramodpantha** [comment]
Thanks a lot Dr. Brant.

**Comment by brantfaircloth** [comment]
no problem!

**Pull request closed without merging**
