### PR TITLE
Submit Assignment 1

### PR DESCRIPTION
**Pull request by reige012**

### CODE REVIEW

**Comment by brantfaircloth** [comment]
Looks good.  You're golden.

**Comment by reige012** [comment]
Cool, thanks. Deleting that was more of a process than expected, but I
finally figured it out. If you delete it and re-fork it with the same name
it automatically downloads your previous commits. For some strange reason.
I had to rename the fork and then I could restart.

Just in case future people have the same issue.

On Fri, Jan 15, 2016 at 11:01 AM, Brant Faircloth <notifications@github.com>
wrote:

> Looks good. You're golden.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/biolprogramming/assignment-1/pull/4#issuecomment-172016312>
> .
>



-- 
Ph.D. Student, Louisiana State University
M.S. Biology, Georgia Southern University
Phone: (912)481-5298
Email: areige1@lsu.edu

**Comment by brantfaircloth** [comment]
Actually, you're still not quite golden - your answers need to be in a directory that is your username, within the ```answers``` directory.

**Comment by reige012** [comment]
I'm sorry. I don't know why I'm struggling so much with this. The assigment
was a breeze except for Github.  I hope I finally got it figured out. It
looked different when I forked it this time.

On Mon, Jan 18, 2016 at 8:29 AM, Brant Faircloth <notifications@github.com>
wrote:

> Actually, you're still not quite golden - your answers need to be in a
> directory that is your username, within the answers directory.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/biolprogramming/assignment-1/pull/4#issuecomment-172540750>
> .
>



-- 
Ph.D. Student, Louisiana State University
M.S. Biology, Georgia Southern University
Phone: (912)481-5298
Email: areige1@lsu.edu

**Comment by brantfaircloth** [comment]
you’re all good now.

-b

**Pull request closed without merging**
